name       : openjml            # name of the package
version    : 1.7.3.20150406-1   # version of the package
kind       : tool               # one of tool or spec(s)
description: OpenJML is a tool set for JML, built on the OpenJDK framework for Java. 

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com



# a list of the named and versioned packages that must be installed before
# installing 

#
# assets that make up THIS package
#

assets:
    - asset   : MAIN
      name    : openjml-dist
      url     : http://jmlspecs.sourceforge.net/openjml.tar.gz
      platform: all
        
# assumes:
#   - cmd: java --version # right now just support cmd -- maybe file exists?
#     contains: 1.7
#     message: "Sorry, but this package requires Java, version 1.7 or higher."


# downloads everything to the .
install:
  - cmd: tar -zxvf MAIN
    description: Unpacking the archive...
    platform: all
