name       : openjml            # name of the package
version    : 1.8.19.20170726    # version of the package
kind       : tool               # one of tool or spec(s)
description: OpenJML is a tool set for JML, built on the OpenJDK framework for Java. 

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com



# a list of the named and versioned packages that must be installed before
# installing 

#
# assets that make up THIS package
#
assets:
    - asset   : MAIN
      name    : openjml-dist
      url     : https://github.com/OpenJML/OpenJML/releases/download/0.8.19/openjml-0.8.18-20170726.tar.gz

      platform: all
        
        
# assumes:
#   - cmd: java --version # right now just support cmd -- maybe file exists?
#     contains: 1.7
#     message: "Sorry, but this package requires Java, version 1.7 or higher."


# downloads everything to the .
install:
  - cmd: tar -zxvf MAIN
    description: Unpacking the archive...
    platform: all
